import Navbar from "@/components/home/Navbar";
import SideBar from "@/components/home/Sidebar";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
// import './globals.css'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <main className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased  h-screen relative`}>
    <Navbar/>
    <div className='flex flex-row'>
        <SideBar/>
        <section className='flex h-screen overflow-auto flex-1 flex-col px-6 pb-6 pt-10 max-md:pb-14 sm:px-14 bg-white'>
            <div className='w-full mt-[58px]'>
                  {children}
            </div>
        </section>
    </div>
</main>
  );
}
